spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/youtube
          jwk-set-uri: http://localhost:8080/realms/youtube/protocol/openid-connect/certs

server:
  port: 8081